### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LizQuinlan**

### CODE REVIEW

**Review by EstherPlomp — COMMENTED** [review]
Hi Liz! 

Thanks for changing the readme file! Looks great. Do you maybe want to add some information about the separate folders?

Esther

**Comment by LizQuinlan** [comment]
Yes, I think that would be good!

Liz

**Review by EstherPlomp — APPROVED** [review]
Looks fantastic, thanks for adding that!

**Comment by EstherPlomp** [comment]
Add a comment after closing

**Pull request merged**
